
services:
  - type: web
    name: protokol13-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
